<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

class UpdateDatacenterIpRangesCommand extends Command
{
    protected $signature = 'bot-protection:update-datacenter-ip-ranges';

    protected $description = 'Fetch the announced prefixes of the datacenter ASNs from RIPEstat';

    public function handle(): int
    {
        /** @var array<int, array<int, array{0: string, 1: string, 2: int}>> $ranges */
        $ranges = [4 => [], 6 => []];

        foreach (config('bot-protection.datacenter_asns') as $asn => $name) {
            $this->info("Fetching prefixes of AS{$asn} ({$name})...");

            $prefixes = Http::retry(3, 1000)
                ->timeout(60)
                ->get('https://stat.ripe.net/data/announced-prefixes/data.json', [
                    'resource' => "AS{$asn}",
                    'sourceapp' => 'dnsrecords-io',
                ])
                ->throw()
                ->json('data.prefixes.*.prefix', []);

            foreach ($prefixes as $prefix) {
                $range = $this->rangeForPrefix($prefix);

                if (! $range) {
                    continue;
                }

                $ranges[$range['family']][] = [$range['start'], $range['end'], $asn];
            }
        }

        $ranges = array_map(fn (array $familyRanges) => $this->mergeOverlappingRanges($familyRanges), $ranges);

        file_put_contents(config('bot-protection.datacenter_ip_ranges_path'), $this->toPhpFile($ranges));

        $this->comment('Stored '.count($ranges[4]).' IPv4 and '.count($ranges[6]).' IPv6 ranges.');

        return self::SUCCESS;
    }

    /** @param array<int, array<int, array{0: string, 1: string, 2: int}>> $ranges */
    protected function toPhpFile(array $ranges): string
    {
        $lines = ['<?php', '', '/* Generated by `php artisan bot-protection:update-datacenter-ip-ranges`. */', '', 'return ['];

        foreach ($ranges as $family => $familyRanges) {
            $lines[] = "    {$family} => [";

            foreach ($familyRanges as [$start, $end, $asn]) {
                $lines[] = "        ['{$start}', '{$end}', {$asn}],";
            }

            $lines[] = '    ],';
        }

        $lines[] = '];';

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /** @return array{family: int, start: string, end: string}|null */
    protected function rangeForPrefix(string $prefix): ?array
    {
        [$address, $prefixLength] = array_pad(explode('/', $prefix, 2), 2, null);

        $packedAddress = @inet_pton($address);

        if ($packedAddress === false) {
            return null;
        }

        $totalBits = strlen($packedAddress) * 8;

        $prefixLength = $prefixLength === null ? $totalBits : (int) $prefixLength;

        $start = '';
        $end = '';

        foreach (str_split($packedAddress) as $index => $byte) {
            $networkBitsInByte = max(0, min(8, $prefixLength - $index * 8));

            $hostMask = (0xFF >> $networkBitsInByte) & 0xFF;

            $start .= chr(ord($byte) & ~$hostMask & 0xFF);
            $end .= chr(ord($byte) | $hostMask);
        }

        return [
            'family' => strlen($packedAddress) === 4 ? 4 : 6,
            'start' => bin2hex($start),
            'end' => bin2hex($end),
        ];
    }

    /**
     * @param array<int, array{0: string, 1: string, 2: int}> $ranges
     *
     * @return array<int, array{0: string, 1: string, 2: int}>
     */
    protected function mergeOverlappingRanges(array $ranges): array
    {
        usort($ranges, fn (array $first, array $second) => strcmp($first[0], $second[0]) ?: strcmp($second[1], $first[1]));

        $mergedRanges = [];

        foreach ($ranges as $range) {
            $lastIndex = count($mergedRanges) - 1;

            if ($lastIndex >= 0) {
                $lastRange = $mergedRanges[$lastIndex];

                if ($this->overlaps($lastRange, $range) || $this->isAdjacentRangeOfSameAsn($lastRange, $range)) {
                    if (strcmp($range[1], $lastRange[1]) > 0) {
                        $mergedRanges[$lastIndex][1] = $range[1];
                    }

                    continue;
                }
            }

            $mergedRanges[] = $range;
        }

        return $mergedRanges;
    }

    /**
     * @param array{0: string, 1: string, 2: int} $range
     * @param array{0: string, 1: string, 2: int} $nextRange
     */
    protected function overlaps(array $range, array $nextRange): bool
    {
        return strcmp($nextRange[0], $range[1]) <= 0;
    }

    /**
     * @param array{0: string, 1: string, 2: int} $range
     * @param array{0: string, 1: string, 2: int} $nextRange
     */
    protected function isAdjacentRangeOfSameAsn(array $range, array $nextRange): bool
    {
        if ($range[2] !== $nextRange[2]) {
            return false;
        }

        return $this->incrementHexAddress($range[1]) === $nextRange[0];
    }

    protected function incrementHexAddress(string $hexAddress): string
    {
        $bytes = array_map('ord', str_split(hex2bin($hexAddress)));

        for ($index = count($bytes) - 1; $index >= 0; $index--) {
            if ($bytes[$index] < 0xFF) {
                $bytes[$index]++;

                break;
            }

            $bytes[$index] = 0;
        }

        return bin2hex(implode('', array_map('chr', $bytes)));
    }
}
